node {
    def mvnHome
    stage('Preparation') { // for display purposes
        // Get some code from a GitHub repository
         git branch: 'naveenscript', url: 'https://github.com/TarakaPhaneendra/Jenkinsscript1.git'
        // Get the Maven tool.
        // ** NOTE: This 'M3' Maven tool must be configured
        // **       in the global configuration.
        mvnHome = tool 'MAVEN_HOME"'
    }
    stage('Build') {
        // Run the maven build
        withEnv(["MVN_HOME=$mvnHome"]) {
            if (isUnix()) {
                sh '"$MVN_HOME/bin/mvn" -Dmaven.test.failure.ignore clean package'
            } else {
                bat(/"%MVN_HOME%\bin\mvn" -Dmaven.test.failure.ignore clean package/)
            }
        }
    }
  stage('Results') {
    steps {
        // Publish JUnit-style reports generated by TestNG
        junit 'target/surefire-reports/*.xml'

        // Archive all JAR files created during the build
        archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
    }
}

}

